{% set version = "6.7.3" %}

package:
  name: qt6-networkauth
  version: {{ version }}

source:
  url: https://download.qt.io/official_releases/qt/{{ version.rpartition('.')[0] }}/{{ version }}/submodules/qtnetworkauth-everywhere-src-{{ version }}.tar.xz
  sha256: 6b9a75a5e8829c56f4cfcdd146082882896b87eda380996f9cc34936504a13b7

build:
  number: 0
  detect_binary_files_with_prefix: true
  run_exports:
    - {{ pin_subpackage('qt6-networkauth', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - ninja
    - perl
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - qt6-main {{ version }}             # [build_platform != target_platform]

  host:
    - qt6-main {{ version }}

test:
  commands:
    {% set qt_libs = ["NetworkAuth"] %}
    {% for each_qt_lib in qt_libs %}
    - test -d $PREFIX/include/qt6/Qt{{ each_qt_lib }}  # [unix]
    - test -f $PREFIX/lib/libQt6{{ each_qt_lib }}${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\include\\qt6\\Qt{{ each_qt_lib }} exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\Qt6{{ each_qt_lib }}.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\Qt6{{ each_qt_lib }}.dll exit 1  # [win]
    {% endfor %}

about:
  home: http://qt-project.org
  license: GPL-3.0-only
  license_file:
    - LICENSES/GPL-3.0-only.txt
    - LICENSES/BSD-3-Clause.txt
    - LICENSES/GFDL-1.3-no-invariants-only.txt
    - LICENSES/LicenseRef-Qt-Commercial.txt
    - LICENSES/Qt-GPL-exception-1.0.txt
  summary: Qt Network Authentication
  description: |
    Qt Network Authorization provides a set of APIs that enable Qt applications
    to obtain limited access to online accounts and HTTP services without
    exposing users' passwords.

  doc_url: http://doc.qt.io/
  dev_url: https://github.com/qt/qtopcua

extra:
  recipe-maintainers:
    - hmaarrfk
    - conda-forge/qt-main
  feedstock-name: qt-networkauth
